openapi: 3.0.0
info:
  title: Membership Management API
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []

paths:
  /auth/register:
    $ref: './auth.yaml#/paths/~1auth~1register/post'
  /auth/login:
    $ref: './auth.yaml#/paths/~1auth~1login/post'

  /payments:
    $ref: './payments.yaml#/paths/~1payments/post'
  /payments/event/{eventId}:
    $ref: './payments.yaml#/paths/~1payments~1event~1{eventId}/get'

  /events:
    $ref: './events.yaml#/paths/~1events/get'
